package org.rm.automation.utils;

import org.testng.Reporter;

/**
 * ReportManager uses the Reporter available class from TestNG, it's used 
 * for test methods to log messages that will be included in the HTML reports generated by TestNG. 
 * 
 */
public class ReportManager {
	/*
	 * The "org.uncommons.reportng.escape-output" is used to turn off escaping for log output in the reports.
	 */
	private static String REPORTNG_ESCAPE_OUTPUT = "org.uncommons.reportng.escape-output";
	
	/**
	 * @param filePath
	 * The method create a string that will be sent to the Reporter, so that it can log
	 * new tag elements and values (screenshot) to the HTML report.
	 */
	public static void appendImageHyperLink(String filePath){
		enableHtmlReportEdition();
		
		String failedTestImageLinkTag = "<b>Screenshot: </b><br/>"
			+ "<a href=\"[filePath]"
	        + "\"><img src=\"[filePath]"
	        + "\" alt=\"\"" + "height='400' width='600'/><br/>";
		failedTestImageLinkTag = failedTestImageLinkTag.replace("[filePath]", filePath);
		
		Reporter.log(failedTestImageLinkTag); 
	}
	
	/**
	 * @param testName
	 * @param message
	 * The method create a string that will be sent to the Reporter, so that it can log
	 * new tag elements and values (test name and message) to the HTML report. 
	 */
	public static void appendTestCaseErrorMessage(String testName, String message){
		enableHtmlReportEdition();
		
		String errorMessageTag = "<a href=\"javascript:toggleElement('[testCaseName]', 'block')\" title=\"Click to expand/collapse\"><b>Test Case Title: [testCaseName]</b></a><br />";
		errorMessageTag = errorMessageTag + "<div class=\"stackTrace\" id=\"[testCaseName]\" style=\"display: none;\">[message]</div><br />";
		errorMessageTag = errorMessageTag
			.replace("[testCaseName]", testName)
			.replace("[message]", message);
		
		Reporter.log(errorMessageTag); 
	}
	
	/**
	 * @param testName
	 * The method create a string that will be sent to the Reporter, so that it can log
	 * new tag elements and values (test name) to the HTML report.
	 */
	public static void appendTestCaseName(String testName){
		enableHtmlReportEdition();	
		
		String errorMessageTag = "<b>Test Case Title: [testCaseName]</b><br/>";
		errorMessageTag = errorMessageTag
			.replace("[testCaseName]", testName);
		
		Reporter.log(errorMessageTag); 
	}
	
	/**
	 * The method enables HTML report edition.
	 */
	private static void enableHtmlReportEdition(){
		System.setProperty(REPORTNG_ESCAPE_OUTPUT , "false");
	}
}